window.RELEMBRE_DATA = [
  {
    title: "Gestação: adaptações maternas e lógica fisiológica",
    icon: "🤰",
    content: [
      { type: "h3", text: "Conceito central" },
      { type: "p", text: "A gestação induz adaptação multissistêmica materna para manter perfusão uteroplacentária, crescimento fetal e preparo para parto/lactação." },
      { type: "h3", text: "Cardiovascular" },
      { type: "p", text: "Volume plasmático aumenta → expande a volemia materna → melhora enchimento vascular e perfusão uteroplacentária." },
      { type: "p", text: "Débito cardíaco aumenta por aumento de volume sistólico e frequência cardíaca → garante maior oferta de O₂ e nutrientes ao concepto." },
      { type: "p", text: "Resistência vascular periférica diminui por vasodilatação e circulação placentária de baixa resistência → favorece fluxo uterino." },
      { type: "p", text: "PA tende a cair no 2º trimestre → queda fisiológica por redução da resistência periférica; retorno progressivo depois." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Hipotensão discreta pode ser fisiológica." },
      { type: "p", text: "Hipertensão persistente foge da adaptação normal e exige investigação de doença hipertensiva da gestação." },
      { type: "h3", text: "Hematológico" },
      { type: "p", text: "Expansão plasmática > aumento da massa eritrocitária → hemodiluição → “anemia fisiológica da gestação”." },
      { type: "p", text: "Estado pró-coagulante → aumento relativo da hemostasia para proteção no parto, mas com maior risco tromboembólico." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Nem toda queda de Hb é anemia ferropriva." },
      { type: "p", text: "Gestação = risco trombótico aumentado." },
      { type: "h3", text: "Respiratório" },
      { type: "p", text: "Ventilação alveolar aumenta → maior eliminação de CO₂ materno-fetal e melhor gradiente de trocas gasosas." },
      { type: "p", text: "Dispneia fisiológica pode ocorrer por hiperventilação gestacional, sem hipoxemia nem grande esforço respiratório." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Dispneia leve pode ser fisiológica." },
      { type: "p", text: "Dispneia com dessaturação, dor torácica, tiragem ou instabilidade = patológica até prova em contrário." },
      { type: "h3", text: "Renal e hidroeletrolítico" },
      { type: "p", text: "Fluxo plasmático renal e TFG aumentam → maior depuração de solutos e adaptação ao volume extracelular expandido." },
      { type: "p", text: "Retenção de sódio e água ajuda na expansão da volemia." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Edema leve pode ser fisiológico." },
      { type: "p", text: "Proteinúria significativa não é adaptação normal." },
      { type: "h3", text: "Endócrino-metabólico" },
      { type: "p", text: "A placenta atua como órgão endócrino transitório." },
      { type: "p", text: "Resistência insulínica gestacional → poupa glicose para o feto → mecanismo fisiológico mediado por hormônios placentários." },
      { type: "p", text: "Se esse mecanismo excede a capacidade pancreática materna → diabetes gestacional." },
      { type: "h3", text: "Musculoesquelético e tegumentar" },
      { type: "p", text: "Frouxidão ligamentar → facilita adaptações pélvicas ao parto." },
      { type: "p", text: "Mudança do centro de gravidade → hiperlordose/lombalgia mecânica." },
      { type: "p", text: "Hiperpigmentação e estrias → efeito hormonal + distensão tecidual." }
    ]
  },
  {
    title: "Placenta: desenvolvimento, estrutura e função",
    icon: "🌸",
    content: [
      { type: "h3", text: "Conceito central" },
      { type: "p", text: "A placenta é o órgão de interface materno-fetal, responsável por trocas, regulação endócrina e modulação imunológica." },
      { type: "h3", text: "Formação" },
      { type: "p", text: "Inicia-se após a implantação do blastocisto." },
      { type: "p", text: "A porção fetal deriva do trofoblasto/córion; a porção materna relaciona-se à decídua." },
      { type: "p", text: "Vilosidades coriônicas = unidade anatômico-funcional da troca placentária." },
      { type: "h3", text: "Anatomia macro" },
      { type: "p", text: "Face fetal: lisa, recoberta por âmnio, com inserção do cordão." },
      { type: "p", text: "Face materna: irregular, voltada ao útero." },
      { type: "p", text: "Cordão umbilical: 2 artérias + 1 veia." },
      { type: "h3", text: "Circulação" },
      { type: "p", text: "Artérias umbilicais levam sangue fetal à placenta." },
      { type: "p", text: "Veia umbilical retorna sangue oxigenado ao feto." },
      { type: "p", text: "Sangue materno banha o espaço interviloso." },
      { type: "p", text: "Sangue fetal circula nos vasos vilosos." },
      { type: "p", text: "Não há mistura direta habitual entre sangue materno e fetal." },
      { type: "h3", text: "Funções" },
      { type: "p", text: "Troca gasosa → placenta exerce função pulmonar fetal." },
      { type: "p", text: "Transporte de nutrientes → função absortiva/metabólica." },
      { type: "p", text: "Excreção de metabólitos fetais → função excretora." },
      { type: "p", text: "Barreira seletiva → proteção parcial, não absoluta." },
      { type: "p", text: "Função endócrina → síntese hormonal." },
      { type: "p", text: "Função imunológica → modulação da interface materno-fetal." },
      { type: "h3", text: "Endocrinologia placentária" },
      { type: "p", text: "hCG mantém o corpo lúteo no início da gestação." },
      { type: "p", text: "Progesterona mantém o endométrio e reduz contratilidade uterina." },
      { type: "p", text: "Estrogênios estimulam crescimento uterino e mamário." },
      { type: "p", text: "hPL/hCS induz resistência insulínica e lipólise materna → favorece disponibilidade energética fetal." }
    ]
  },
  {
    title: "Imunologia da gestação",
    icon: "🛡️",
    content: [
      { type: "h3", text: "Conceito central" },
      { type: "p", text: "O feto é um semiálogo imunológico, mas a gestação evolui porque existe tolerância materno-fetal ativa." },
      { type: "h3", text: "Mecanismo" },
      { type: "p", text: "O trofoblasto reduz ativação imune agressiva materna." },
      { type: "p", text: "A decídua participa da regulação do microambiente imune." },
      { type: "p", text: "Ocorre privilégio imunológico relativo, e não imunossupressão absoluta." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Falha da tolerância/placentação → pode contribuir para:" },
      { type: "p", text: "insuficiência placentária" },
      { type: "p", text: "restrição de crescimento fetal" },
      { type: "p", text: "pré-eclâmpsia" }
    ]
  },
  {
    title: "Patologias placentárias e repercussões materno-fetais",
    icon: "⚠️",
    content: [
      { type: "h3", text: "Conceito central" },
      { type: "p", text: "Lesão placentária = prejuízo de perfusão e troca = repercussão fetal e materna." },
      { type: "h3", text: "Alterações de implantação/perfusão" },
      { type: "p", text: "Implantação anormal → vilosidades e invasão trofoblástica inadequadas." },
      { type: "p", text: "Perfusão uteroplacentária reduzida → menor troca gasosa/nutricional." },
      { type: "p", text: "Consequência fetal: restrição de crescimento, hipóxia crônica, sofrimento fetal." },
      { type: "h3", text: "Alterações inflamatórias/infecciosas" },
      { type: "p", text: "Inflamação placentária compromete a integridade funcional da interface de trocas." },
      { type: "p", text: "Pode repercutir em prematuridade e comprometimento fetal." },
      { type: "h3", text: "Pré-eclâmpsia" },
      { type: "p", text: "Doença relacionada a placentação anormal e disfunção endotelial materna sistêmica." },
      { type: "p", text: "A raiz fisiopatológica está na placenta mal perfundida, não apenas na pressão arterial elevada." },
      { type: "p", text: "Manifesta-se com hipertensão e frequentemente proteinúria/sinais de lesão orgânica." },
      { type: "h3", text: "Eclâmpsia" },
      { type: "p", text: "É a complicação convulsiva da doença hipertensiva gestacional." },
      { type: "h3", text: "Pegadinha médica" },
      { type: "p", text: "Pré-eclâmpsia não deve ser decorada como “HAS + proteinúria”." },
      { type: "p", text: "O conceito correto é: síndrome placentário-endotelial materna." }
    ]
  },
  {
    title: "Parto e puerpério",
    icon: "👶",
    content: [
      { type: "h3", text: "Parto" },
      { type: "p", text: "Trabalho de parto = transição do útero de estado quiescente para contração coordenada e eficaz." },
      { type: "p", text: "Prostaglandinas e ocitocina participam da ativação miometrial." },
      { type: "p", text: "Contração uterina → apagamento/dilatação cervical → progressão fetal → expulsão." },
      { type: "h3", text: "Puerpério" },
      { type: "p", text: "É a fase de reversão das adaptações gravídicas." },
      { type: "p", text: "Ocorre involução uterina por regressão do volume uterino." },
      { type: "p", text: "Há reorganização hemodinâmica e hormonal rápida após a saída da placenta." },
      { type: "h3", text: "Lactação" },
      { type: "p", text: "Prolactina = síntese de leite." },
      { type: "p", text: "Ocitocina = ejeção do leite." },
      { type: "p", text: "Sucção ativa reflexo neuroendócrino hipotálamo-hipofisário → mantém lactação." },
      { type: "h3", text: "Pegadinha clássica" },
      { type: "p", text: "Produção ≠ ejeção:" },
      { type: "p", text: "prolactina produz" },
      { type: "p", text: "ocitocina ejeta" }
    ]
  },
  {
    title: "Neonatologia essencial",
    icon: "🍼",
    content: [
      { type: "h3", text: "Transição cardiorrespiratória" },
      { type: "p", text: "Nascimento = transição da circulação fetal dependente da placenta para circulação neonatal dependente do pulmão." },
      { type: "p", text: "A expansão pulmonar reduz a resistência vascular pulmonar." },
      { type: "p", text: "O fluxo pulmonar aumenta e os shunts fetais iniciam fechamento funcional." },
      { type: "h3", text: "Avaliação inicial do RN" },
      { type: "p", text: "Observar:" },
      { type: "p", text: "respiração" },
      { type: "p", text: "FC" },
      { type: "p", text: "tônus" },
      { type: "p", text: "perfusão/cor" },
      { type: "p", text: "atividade" },
      { type: "h3", text: "Prematuridade" },
      { type: "p", text: "Prematuro = imaturidade estrutural e funcional de múltiplos sistemas." },
      { type: "p", text: "Maior vulnerabilidade:" },
      { type: "p", text: "respiratória" },
      { type: "p", text: "térmica" },
      { type: "p", text: "metabólica" },
      { type: "h3", text: "Síndrome da angústia respiratória do RN" },
      { type: "p", text: "Causa principal: deficiência de surfactante." },
      { type: "p", text: "Sem surfactante → maior tensão superficial alveolar → colapso alveolar → atelectasia → hipoxemia." },
      { type: "h3", text: "Icterícia neonatal" },
      { type: "p", text: "RN tem:" },
      { type: "p", text: "maior turnover eritrocitário" },
      { type: "p", text: "conjugação hepática ainda limitada" },
      { type: "p", text: "Resultado: predisposição à hiperbilirrubinemia fisiológica inicial." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Icterícia fisiológica tem limites temporais e de intensidade." },
      { type: "p", text: "Icterícia precoce/intensa/prolongada = investigar patologia." }
    ]
  },
  {
    title: "Crescimento e desenvolvimento",
    icon: "📈",
    content: [
      { type: "h3", text: "Conceito central" },
      { type: "p", text: "Crescimento = aumento ponderoestatural." },
      { type: "p", text: "Desenvolvimento = maturação funcional neuropsicomotora e biopsicossocial." },
      { type: "h3", text: "Princípios médicos" },
      { type: "p", text: "Avaliação deve ser longitudinal, não baseada só em medida isolada." },
      { type: "p", text: "Curvas permitem identificar tendência, desaceleração ou desvio." },
      { type: "p", text: "Regressão de marco é sempre sinal de alerta." },
      { type: "h3", text: "Fatores interferentes" },
      { type: "p", text: "nutrição" },
      { type: "p", text: "prematuridade" },
      { type: "p", text: "doença crônica" },
      { type: "p", text: "genética" },
      { type: "p", text: "ambiente familiar/social" },
      { type: "h3", text: "Aplicação clínica" },
      { type: "p", text: "Alteração genética ou malformação pode repercutir em:" },
      { type: "p", text: "motricidade" },
      { type: "p", text: "cognição" },
      { type: "p", text: "linguagem" },
      { type: "p", text: "comportamento" },
      { type: "p", text: "inserção social" }
    ]
  },
  {
    title: "Puericultura e propedêutica pediátrica",
    icon: "🩺",
    content: [
      { type: "h3", text: "Estrutura da avaliação pediátrica" },
      { type: "p", text: "Anamnese pediátrica não é só queixa atual → tem que incluir gestação, parto, período neonatal, alimentação, vacinas, desenvolvimento e ambiente familiar." },
      { type: "p", text: "RN e lactente → perguntar sobre amamentação, ganho de peso, diurese, evacuação, sono, icterícia, marcos do desenvolvimento." },
      { type: "p", text: "Escolar → perguntar rendimento escolar, socialização, hábitos, alimentação, sono, eliminação, atividade física." },
      { type: "p", text: "Adolescente → perguntar puberdade, sexualidade, saúde mental, uso de substâncias, relação com família/escola, risco social." },
      { type: "h3", text: "Exame físico" },
      { type: "p", text: "RN → tônus, hidratação, icterícia, fontanelas, ausculta, perfusão, reflexos primitivos, malformações." },
      { type: "p", text: "Lactente/criança → crescimento, estado nutricional, sinais respiratórios, exame abdominal, neurológico e dermatológico." },
      { type: "p", text: "Adolescente → crescimento, estadiamento puberal, PA, IMC, saúde mental e exame guiado pela queixa." },
      { type: "h3", text: "Vigilância do desenvolvimento" },
      { type: "p", text: "Não basta “ver se a criança está bem”." },
      { type: "p", text: "Tem que avaliar:" },
      { type: "p", text: "marcos motores" },
      { type: "p", text: "linguagem" },
      { type: "p", text: "interação social" },
      { type: "p", text: "comportamento" },
      { type: "p", text: "aprendizagem" },
      { type: "p", text: "O foco é identificar atraso, regressão ou dissociação entre áreas." },
      { type: "h3", text: "Promoção de saúde" },
      { type: "p", text: "Orientar aleitamento/alimentação complementar." },
      { type: "p", text: "Orientar sono e rotina." },
      { type: "p", text: "Orientar prevenção de acidentes." },
      { type: "p", text: "Orientar estímulo ao desenvolvimento." },
      { type: "p", text: "Conferir vacinação." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Puericultura é consulta de prevenção + rastreio + seguimento longitudinal." },
      { type: "p", text: "O objetivo é detectar alteração antes de virar doença manifesta." }
    ]
  },
  {
    title: "Triagem pré-natal",
    icon: "🧪",
    content: [
      { type: "h3", text: "Conceito" },
      { type: "p", text: "Triagem pré-natal = rastrear risco materno e fetal precocemente, antes de complicação instalada." },
      { type: "h3", text: "O que precisa ser avaliado" },
      { type: "p", text: "Confirmar gestação e idade gestacional → porque o tempo gestacional muda interpretação clínica e conduta." },
      { type: "p", text: "Identificar condições maternas prévias → hipertensão, diabetes, anemia, infecções, doença renal, autoimune, endocrinopatias." },
      { type: "p", text: "Rastrear infecções importantes → porque algumas alteram desfecho fetal, transmissão vertical ou manejo do parto." },
      { type: "p", text: "Avaliar risco metabólico → especialmente intolerância à glicose/diabetes gestacional." },
      { type: "p", text: "Avaliar risco hematológico → anemia, incompatibilidades e sangramentos." },
      { type: "p", text: "Avaliar crescimento e vitalidade fetal → para reconhecer insuficiência placentária/restrição de crescimento." },
      { type: "h3", text: "Como pensar os exames" },
      { type: "p", text: "Exames laboratoriais: servem para rastrear doença materna e risco fetal." },
      { type: "p", text: "Ultrassonografia: serve para datar gestação, avaliar anatomia fetal, placenta, líquido amniótico e crescimento." },
      { type: "p", text: "PA e proteinúria: entram porque ajudam a reconhecer doença hipertensiva da gestação." },
      { type: "h3", text: "O que o aluno precisa entender" },
      { type: "p", text: "Triagem não fecha diagnóstico." },
      { type: "p", text: "Resultado alterado = investigar, repetir, confirmar ou encaminhar." },
      { type: "p", text: "O valor da triagem está no momento certo + interpretação clínica." },
      { type: "h3", text: "Aconselhamento no pré-natal — o que deve ser dito" },
      { type: "p", text: "Explicar sinais de alarme: sangramento, perda de líquido, cefaleia forte, escotomas, dor abdominal intensa, redução de movimentos fetais." },
      { type: "p", text: "Orientar adesão ao seguimento: consultas regulares mudam desfecho materno-fetal." },
      { type: "p", text: "Orientar nutrição, ganho ponderal e suplementação quando indicada." },
      { type: "p", text: "Orientar evitar álcool, tabaco e drogas." },
      { type: "p", text: "Orientar vacinação, atividade física quando apropriada e uso racional de medicamentos." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "Pré-natal bem feito diminui atraso diagnóstico de:" },
      { type: "p", text: "pré-eclâmpsia" },
      { type: "p", text: "diabetes gestacional" },
      { type: "p", text: "infecção materna" },
      { type: "p", text: "restrição de crescimento fetal" },
      { type: "p", text: "sofrimento fetal" }
    ]
  },
  {
    title: "Triagem neonatal",
    icon: "👣",
    content: [
      { type: "h3", text: "Conceito" },
      { type: "p", text: "Triagem neonatal = rastrear doenças ainda assintomáticas no RN para evitar sequelas irreversíveis." },
      { type: "h3", text: "O que é específico da triagem neonatal" },
      { type: "p", text: "1. Rastreio metabólico/endócrino" },
      { type: "p", text: "Teste do pezinho → pesquisa doenças que podem parecer silenciosas no início, mas causam dano neurológico, endócrino ou metabólico se não forem tratadas cedo." },
      { type: "p", text: "O rastreio de hipotireoidismo congênito é essencial porque a deficiência de hormônio tireoidiano no RN pode comprometer crescimento e desenvolvimento neurológico se não for tratada rapidamente." },
      { type: "p", text: "2. Rastreio auditivo" },
      { type: "p", text: "Objetivo: detectar perda auditiva precoce." },
      { type: "p", text: "Importância médica: audição alterada compromete aquisição de linguagem e desenvolvimento neuropsicomotor." },
      { type: "p", text: "3. Rastreio ocular" },
      { type: "p", text: "Objetivo: identificar alterações que ameaçam visão." },
      { type: "p", text: "Importância médica: algumas lesões são silenciosas no início, mas o atraso no diagnóstico piora prognóstico visual." },
      { type: "p", text: "4. Rastreio de cardiopatia congênita crítica" },
      { type: "p", text: "Objetivo: identificar RN aparentemente bem, mas com cardiopatia dependente de conduto ou com hipoxemia oculta." },
      { type: "p", text: "Importância médica: o RN pode descompensar rapidamente após fechamento do canal arterial." },
      { type: "h3", text: "O que precisa ser entendido fisiologicamente" },
      { type: "p", text: "O RN pode parecer normal nas primeiras horas/dias e ainda ter doença grave." },
      { type: "p", text: "Triagem neonatal existe porque esperar sintomas pode ser tarde demais." },
      { type: "h3", text: "Como interpretar" },
      { type: "p", text: "Exame alterado não é diagnóstico definitivo." },
      { type: "p", text: "Exame alterado exige:" },
      { type: "p", text: "confirmação" },
      { type: "p", text: "avaliação clínica" },
      { type: "p", text: "seguimento" },
      { type: "p", text: "Exame normal não substitui exame físico neonatal." },
      { type: "h3", text: "Importância médica" },
      { type: "p", text: "O maior valor da triagem neonatal é prevenir:" },
      { type: "p", text: "atraso neuropsicomotor" },
      { type: "p", text: "lesão neurológica" },
      { type: "p", text: "crise metabólica" },
      { type: "p", text: "perda auditiva/visual não tratada" },
      { type: "p", text: "descompensação cardiovascular inesperada" }
    ]
  },
  {
    title: "Doenças hereditárias/genéticas e malformações do SNC",
    icon: "🧬",
    content: [
      { type: "p", text: "Alterações genéticas podem mudar o desenvolvimento do sistema nervoso." },
      { type: "p", text: "Isso pode gerar malformações, atraso do desenvolvimento e déficits funcionais." },
      { type: "h3", text: "Suspeição clínica" },
      { type: "p", text: "História familiar positiva." },
      { type: "p", text: "Dismorfismos." },
      { type: "p", text: "Atraso global do desenvolvimento." },
      { type: "p", text: "Regressão." },
      { type: "p", text: "Múltiplas malformações." },
      { type: "p", text: "Achados neurológicos associados." },
      { type: "h3", text: "Impacto" },
      { type: "p", text: "Pode haver repercussão motora." },
      { type: "p", text: "Pode haver repercussão cognitiva." },
      { type: "p", text: "Pode haver repercussão sensorial." },
      { type: "p", text: "O impacto costuma ser global." }
    ]
  },
  {
    title: "Puberdade e adolescência normal",
    icon: "🌼",
    content: [
      { type: "p", text: "Puberdade é maturação sexual." },
      { type: "p", text: "Adolescência é uma fase mais ampla, com mudanças biológicas, emocionais e sociais." },
      { type: "h3", text: "Puberdade" },
      { type: "p", text: "Existe sequência esperada de eventos puberais." },
      { type: "p", text: "O ritmo pode variar dentro da normalidade." },
      { type: "p", text: "O importante é reconhecer quando foge muito do esperado." },
      { type: "h3", text: "Adolescência" },
      { type: "p", text: "Há construção de identidade e autonomia." },
      { type: "p", text: "A relação com pares e família muda bastante." },
      { type: "p", text: "A abordagem clínica deve ser ética e sem julgamento." }
    ]
  },
  {
    title: "Gravidez e anticoncepção na adolescência",
    icon: "💗",
    content: [
      { type: "h3", text: "Conceito" },
      { type: "p", text: "Aconselhamento contraceptivo não é “falar método”." },
      { type: "p", text: "É avaliar contexto, risco, autonomia, adesão e proteção dupla." },
      { type: "h3", text: "O que tem que ser abordado" },
      { type: "p", text: "Se há atividade sexual ou risco de iniciar." },
      { type: "p", text: "Se há desejo reprodutivo ou não." },
      { type: "p", text: "Se a adolescente consegue aderir ao método." },
      { type: "p", text: "Se existe risco de IST, porque contracepção e prevenção de IST não são a mesma coisa." },
      { type: "p", text: "Se há violência, coerção ou vulnerabilidade social." },
      { type: "h3", text: "O que deve ser dito no aconselhamento" },
      { type: "p", text: "Explicar os métodos de forma clara e sem julgamento." },
      { type: "p", text: "Explicar eficácia prática, não só eficácia teórica." },
      { type: "p", text: "Explicar que o método ideal é o que a paciente consegue usar corretamente e manter." },
      { type: "p", text: "Explicar que preservativo é importante mesmo com outro método, porque protege contra IST." },
      { type: "p", text: "Explicar efeitos adversos, contraindicações e quando retornar." },
      { type: "h3", text: "Como o aconselhamento deve ser" },
      { type: "p", text: "Individualizado" },
      { type: "p", text: "Confidencial" },
      { type: "p", text: "Baseado em autonomia progressiva" },
      { type: "p", text: "Sem postura moralizante" },
      { type: "p", text: "Com linguagem compatível com a idade" },
      { type: "h3", text: "Gravidez na adolescência — o que precisa ser abordado" },
      { type: "p", text: "Risco biológico: pré-natal tardio, maior vulnerabilidade nutricional, complicações por cuidado inadequado." },
      { type: "p", text: "Risco psicossocial: evasão escolar, vulnerabilidade econômica, sofrimento emocional." },
      { type: "p", text: "Conduta correta: acolher, garantir pré-natal, organizar rede de apoio e rastrear risco social/mental." }
    ]
  },
  {
    title: "Adolescente em situação de risco e saúde mental",
    icon: "🌧️",
    content: [
      { type: "h3", text: "O que precisa ser investigado" },
      { type: "p", text: "Violência física, sexual ou doméstica" },
      { type: "p", text: "Uso de álcool, tabaco e outras drogas" },
      { type: "p", text: "Autoagressão / ideação suicida" },
      { type: "p", text: "Humor deprimido, ansiedade, irritabilidade persistente" },
      { type: "p", text: "Queda escolar e isolamento" },
      { type: "p", text: "Conflito familiar intenso" },
      { type: "p", text: "Exposição a risco sexual/social" },
      { type: "h3", text: "Como isso aparece na prática" },
      { type: "p", text: "Nem sempre vem como “tristeza”." },
      { type: "p", text: "Pode vir como:" },
      { type: "p", text: "cefaleia recorrente" },
      { type: "p", text: "dor abdominal sem causa orgânica clara" },
      { type: "p", text: "insônia" },
      { type: "p", text: "automutilação" },
      { type: "p", text: "queda brusca no desempenho escolar" },
      { type: "p", text: "agressividade" },
      { type: "p", text: "recusa alimentar" },
      { type: "h3", text: "O que o médico precisa fazer" },
      { type: "p", text: "Criar ambiente seguro de escuta." },
      { type: "p", text: "Falar parte da consulta a sós com o adolescente, quando apropriado." },
      { type: "p", text: "Avaliar risco agudo: suicídio, violência, intoxicação, abuso." },
      { type: "p", text: "Articular família, escola e rede quando necessário." }
    ]
  },
  {
    title: "Patologias pediátricas frequentes e sinais de gravidade",
    icon: "🚨",
    content: [
      { type: "h3", text: "Respiratório" },
      { type: "p", text: "Taquipneia importante." },
      { type: "p", text: "Tiragem, gemência, batimento de asa nasal." },
      { type: "p", text: "Cianose ou dessaturação." },
      { type: "p", text: "Hipoventilação/redução do esforço em criança exausta." },
      { type: "h3", text: "Neurológico" },
      { type: "p", text: "Sonolência excessiva." },
      { type: "p", text: "Irritabilidade inconsolável." },
      { type: "p", text: "Rebaixamento do nível de consciência." },
      { type: "p", text: "Convulsão." },
      { type: "p", text: "Rigidez de nuca ou alteração importante de comportamento." },
      { type: "h3", text: "Hemodinâmico" },
      { type: "p", text: "Perfusão periférica ruim." },
      { type: "p", text: "Extremidades frias." },
      { type: "p", text: "Tempo de enchimento capilar prolongado." },
      { type: "p", text: "Taquicardia desproporcional." },
      { type: "p", text: "Hipotensão é sinal tardio e grave." },
      { type: "h3", text: "Hidratação/metabólico" },
      { type: "p", text: "Recusa alimentar importante." },
      { type: "p", text: "Oligúria." },
      { type: "p", text: "Sinais de desidratação moderada/importante." },
      { type: "p", text: "Perda ponderal relevante no lactente." },
      { type: "h3", text: "Regra prática" },
      { type: "p", text: "Criança que para de compensar piora rápido." },
      { type: "p", text: "Em pediatria, “esperar para ver” pode ser cilada premium." }
    ]
  },
  {
    title: "Indicações gerais de internação e terapia intensiva pediátrica",
    icon: "🏥",
    content: [
      { type: "h3", text: "Internação" },
      { type: "p", text: "Quando a criança precisa:" },
      { type: "p", text: "hidratação venosa" },
      { type: "p", text: "observação seriada" },
      { type: "p", text: "oxigênio" },
      { type: "p", text: "antibioticoterapia EV" },
      { type: "p", text: "suporte que não dá para garantir em casa" },
      { type: "h3", text: "UTI" },
      { type: "p", text: "Quando há:" },
      { type: "p", text: "insuficiência respiratória" },
      { type: "p", text: "choque" },
      { type: "p", text: "alteração neurológica importante" },
      { type: "p", text: "necessidade de monitorização contínua" },
      { type: "p", text: "risco de deterioração rápida" },
      { type: "h3", text: "Lógica médica" },
      { type: "p", text: "A decisão não depende só do diagnóstico." },
      { type: "p", text: "Depende de:" },
      { type: "p", text: "instabilidade fisiológica" },
      { type: "p", text: "capacidade de compensação" },
      { type: "p", text: "velocidade de piora" },
      { type: "p", text: "necessidade de suporte avançado" }
    ]
  }
];
